package src.Exception;

public class Excep1 {
    public static void main (String[]args){
        System.out.println("1");
        System.out.println("2");
        System.out.println(10/0);// ArithmeticException occur need to handlled this exception used try ,catch,finally block
        System.out.println("4");
        System.out.println("5");
    }

}
